version: '3.1'

services:
  db_django:
    restart: always
    privileged: true
    image: postgres
    container_name: django_db
    networks: 
      - djangonet
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data/:/var/lib/postgresql
      - ./data/postgresql_data:/var/lib/postgresql/data
  web_django:
    restart: always
    privileged: true
    build: ./src
    container_name: django_server
    networks:
      - djangonet
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/code
    ports:
      - "8000:8000"
    depends_on:
      - db_django   
  nginx: 
    restart: always
    container_name: nginx_server
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    depends_on:
      - web_django
    ports:
      - "80:80"
      - "443:443"

 
networks:
  djangonet:
    driver: bridge
    

