version: '3.1'

services:
  db-django:
    restart: always
    privileged: true
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    container_name: standalone-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql-data:/var/lib/postgresql_data
    networks:
    - djangonet
  web-django:
    restart: always
    privileged: true
    command: bash -c "python3 manage.py runserver 0.0.0.0:8080"
    build: ./src
    container_name: standlone-django
    volumes:
      - ./src:/code
    networks:
    - djangonet
    depends_on:
    - db-django
  nginx-django:
    restart: always
    container_name: standlone-nginx
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
    - "8080:80"
    - "8443:443"
    networks:
    - djangonet
    depends_on:
    - web-django

volumes:
  postgresql:
  postgresql-data:
    
networks:
  djangonet:
    driver: bridge

