version: '3.1'

services:
  db_django:
    restart: always
    privileged: true
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    container_name: django_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql-data:/var/lib/postgresql_data
  web:
    restart: always
    privileged: true
    command: bash -c "python3 manage.py runserver 0.0.0.0:8080"
    build: ./src
    container_name: django_server
    volumes:
      - ./src:/code
    depends_on:
      - db_django
  nginx:
    restart: always
    container_name: nginx_server
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=ctfapp.owens-netsec.com
      - LETSENCRYPT_HOST=ctfapp.owens-netsec.com
      - LETSENCRYPT_EMAIL=simonowens157@gmail.com
      - VIRTUAL_PORT=80
    depends_on:
    - web

volumes:
  postgresql:
  postgresql-data:
    
networks:
  default:
    external:
      name: webproxy
