version: '3.1'

services:
  db_django:
    restart: always
    privileged: true
    image: postgres
    container_name: django_db
    networks: 
      - djangonet
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /CTF-scoreboard/data/:/data/web
  web_django:
    restart: always
    privileged: true
    build: .
    container_name: django_server
    networks:
      - djangonet
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - /CTF-scoreboard/src/:/code
    ports:
      - "8000:8000"
    depends_on:
      - db_django

networks:
  djangonet:
    driver: bridge
